name: linting-wf
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install HTMLHint
        run: npm install --save-dev HTMLHint
      - name: Install Stylelint
        run: npm install --save-dev Stylelint
      - name: Lint HTML Files
        run: npx  HTMLHint "**/*.html"
      - name: Lint CSS Files
        run: npx  Stylelint "**/*.css"
      - name: Display Package.json contents
        run: cat package.json